spring:
  application:
    name: GameCluesBackend
  data:
    redis:
      host: localhost
      port: 6379
server:
  servlet:
    context-path: /api
  port: 8080
igdb:
  client-id: {$CLIENT_ID}
  access-token: {$ACCESS_TOKEN}
  base-url: https://api.igdb.com/v4